### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by zarmeza** [tzvaita/Responsive-site#2]
- Add missing leading zeroes in some decimal values in the CSS, stickler will most likely complain about that.
- Use object-fit: cover in some images to preserve aspect ratio.
- Try to use rems instead of ems whenever possible.
- Fix the styling on the list items.

**Comment by ermin-cahtarevic** [comment]
- Add missing leading zeroes in some decimal values in the CSS, stickler will most likely complain about that.
- In some places you have 0px, just remove the 'px'
- Layout issue on large screens for the main three articles
- 1440px media query is nested inside of 1024px media query
- update the README file!!
